CREATE TABLE `orders` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `active_flag` tinyint(1) DEFAULT '1',
  `created_date` datetime DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `cylinder_type` bigint(20) DEFAULT NULL,
  `is_refill` tinyint(1) DEFAULT '0',
  `quantity` int(11) DEFAULT NULL,
  `refill_count` int(11) DEFAULT NULL,
  `user_id` bigint(20) DEFAULT NULL,
  `gas_id` bigint(20) DEFAULT NULL,
  `status_id` bigint(20) DEFAULT NULL,
  `price` float(11) DEFAULT NULL,
  `delivered_date` datetime DEFAULT NULL,
  `loaded_date` datetime DEFAULT NULL,
  `cancellation_date` DATETIME NULL,
  `delivery_vehicle` BIGINT(20) NULL,
  `admin_id` bigint(20) DEFAULT NULL,
  `address_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_ORDER_GAS_MASTER` FOREIGN KEY (gas_id) REFERENCES `gas_master`(`id`),
  CONSTRAINT `FK_ORDER_ADDRESS` FOREIGN KEY (address_id) REFERENCES `address`(`id`)
);