server.servlet.context-path=/reek

spring.profiles.active = test

#mysql database properties
spring.datasource.username=root
spring.datasource.password=P@ssw0rd
spring.datasource.url=jdbc:mysql://localhost:3306/reek?useSSL=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.flyway.locations=classpath:migration/schema , classpath:migration/master_data
spring.flyway.outOfOrder=true

#logging.level.org.springframework.security=DEBUG
spring.main.allow-bean-definition-overriding=true

#JPA mapping
spring.jpa.show-sql=false
spring.jpa.hibernate.use-new-id-generator-mappings=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

#Server port Redirect
server.port=8080


#firebase


# Other properties

# TLS , port 587
spring.mail.properties.mail.smtp.starttls.enable=true

#AES Encryption
aes.secret.key = chaLLe
aes.salt.value = tokenM

#Loggers
# logging level
logging.level.org.springframework=ERROR
logging.level.com.moderngas=DEBUG

# output to a file
logging.file=/Documents/app.log
