#mysql database properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=P@ssw0rd
spring.datasource.url=jdbc:mysql://localhost:3306/reek?useSSL=false

#Server port Redirect
server.port=8082
spring.mail.host=smtp.gmail.com
spring.mail.port=25
spring.mail.username=abhishekmoderngas@gmail.com
spring.mail.password=abhi567Cyl

#AES Encryption
aes.secret.key = chaLLenge@Reek2022Encrypt
aes.salt.value = tokenModern

#Loggers
# logging level
logging.level.org.springframework=ERROR
logging.level.com.moderngas=DEBUG

# output to a file
logging.file=/Users/hemakeshzanje/Documents/app.log
